In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

In [4]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [5]:
names = ['sepal-width','sepal-length','petal-width','petal-length','Class']

In [6]:
df = pd.read_csv(url , names= names)

In [7]:
df.head()

sepal-width  sepal-length  petal-width  petal-length        Class
0          5.1           3.5          1.4           0.2  Iris-setosa
1          4.9           3.0          1.4           0.2  Iris-setosa
2          4.7           3.2          1.3           0.2  Iris-setosa
3          4.6           3.1          1.5           0.2  Iris-setosa
4          5.0           3.6          1.4           0.2  Iris-setosa

In [8]:
df.tail()

sepal-width  sepal-length  petal-width  petal-length           Class
145          6.7           3.0          5.2           2.3  Iris-virginica
146          6.3           2.5          5.0           1.9  Iris-virginica
147          6.5           3.0          5.2           2.0  Iris-virginica
148          6.2           3.4          5.4           2.3  Iris-virginica
149          5.9           3.0          5.1           1.8  Iris-virginica

In [13]:
df.shape[1]

5

# X = Features/Attributes(Independent) and y = Label(Dependent)

In [15]:
X_features = df.iloc[:, :-1]
print(X_features)
X = X_features.values
y = df.iloc[:, 4].values

     sepal-width  sepal-length  petal-width  petal-length
0            5.1           3.5          1.4           0.2
1            4.9           3.0          1.4           0.2
2            4.7           3.2          1.3           0.2
3            4.6           3.1          1.5           0.2
4            5.0           3.6          1.4           0.2
..           ...           ...          ...           ...
145          6.7           3.0          5.2           2.3
146          6.3           2.5          5.0           1.9
147          6.5           3.0          5.2           2.0
148          6.2           3.4          5.4           2.3
149          5.9           3.0          5.1           1.8

[150 rows x 4 columns]


# Splitting into train and Test : 

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

# Feature Scaling : 

In [38]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

#Here fit() is only applied in X_train , not in X_test

scaler.fit(X_train)

StandardScaler()

In [37]:
# Here transform() is applied to both X_train and X_test 
# Why transform for X_test ? -  as we also have to feature scale our test data 
# Why not explicity fit() the test data ?  - coz the mean calculated for train, should be also used for test to avoid overfitting

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [35]:
X_train

array([[-1.000586  ,  1.38039705, -1.3347608 , -1.30854911],
       [-1.000586  ,  0.88518735, -1.27800272, -1.30854911],
       [-1.71885311, -0.10523206, -1.39151887, -1.30854911],
       [ 0.43594824,  0.88518735,  0.93556232,  1.45552781],
       [ 0.31623705, -0.10523206,  0.65177193,  0.79741425],
       [-0.52174125,  2.12321161, -1.39151887, -1.04530369],
       [-0.88087481,  1.87560676, -1.22124464, -1.30854911],
       [-0.04289651, -0.84804662,  0.76528808,  0.92903697],
       [ 0.55565942, -1.34325632,  0.65177193,  0.40254612],
       [ 1.6330601 , -0.10523206,  1.16259463,  0.53416883],
       [-1.71885311, -0.35283691, -1.3347608 , -1.30854911],
       [ 0.55565942, -0.84804662,  0.65177193,  0.79741425],
       [ 1.51334891, -0.10523206,  1.2193527 ,  1.19228239],
       [ 0.19652586, -0.35283691,  0.42473962,  0.40254612],
       [ 1.15421535,  0.38997764,  1.2193527 ,  1.45552781],
       [ 1.39363772,  0.38997764,  0.53825577,  0.27092341],
       [ 0.91479298, -0.

In [36]:
X_test

array([[-0.28231888, -0.60044177,  0.65177193,  1.06065968],
       [ 0.55565942,  0.63758249,  0.53825577,  0.53416883],
       [ 0.55565942, -0.35283691,  1.04907847,  0.79741425],
       [-1.12029718,  0.14237279, -1.27800272, -1.44017182],
       [-0.04289651, -1.09565147,  0.14094923,  0.00767799],
       [ 0.79508179,  0.38997764,  0.76528808,  1.06065968],
       [-0.16260769,  3.36123587, -1.27800272, -1.04530369],
       [ 0.19652586,  0.88518735,  0.42473962,  0.53416883],
       [ 1.03450417,  0.14237279,  0.36798154,  0.27092341],
       [-0.76116362,  0.88518735, -1.3347608 , -1.30854911],
       [-1.12029718,  0.14237279, -1.27800272, -1.44017182],
       [-0.88087481,  1.1327922 , -1.3347608 , -1.1769264 ],
       [-1.12029718, -1.34325632,  0.42473962,  0.66579154],
       [-0.04289651, -0.84804662,  0.08419115,  0.00767799],
       [ 0.07681468, -0.10523206,  0.76528808,  0.79741425],
       [-1.24000837, -0.10523206, -1.3347608 , -1.44017182],
       [ 1.03450417, -0.

# KNN Algo

In [40]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 3)

# Now using fit() for training data in Model Building to find all the parameters .

classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

# To make predictions on our test data :

In [41]:
y_pred = classifier.predict(X_test)     # Using Predict() for testing data to make predictions using our model.

# Evaluating our Model 

In [25]:
from sklearn.metrics import confusion_matrix, classification_report 

In [26]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  8  0]
 [ 0  2 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.80      1.00      0.89         8
 Iris-virginica       1.00      0.83      0.91        12

       accuracy                           0.93        30
      macro avg       0.93      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30



# Trying with K = 5 

In [28]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors = 5)

classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [29]:
y_pred = classifier.predict(X_test)

In [30]:
from sklearn.metrics import confusion_matrix, classification_report 
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  8  0]
 [ 0  3  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.73      1.00      0.84         8
 Iris-virginica       1.00      0.75      0.86        12

       accuracy                           0.90        30
      macro avg       0.91      0.92      0.90        30
   weighted avg       0.93      0.90      0.90        30



# Trying with K = 1 

In [32]:
classifier = KNeighborsClassifier(n_neighbors = 1)

classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [33]:
y_pred = classifier.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix, classification_report 
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  7  1]
 [ 0  2 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.78      0.88      0.82         8
 Iris-virginica       0.91      0.83      0.87        12

       accuracy                           0.90        30
      macro avg       0.90      0.90      0.90        30
   weighted avg       0.90      0.90      0.90        30

